name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


permissions:
  contents: read
  checks: write
  

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Setup Gradle cache
        uses: gradle/gradle-build-action@v3

      - name: Validate Gradle Wrapper
    
        uses: gradle/wrapper-validation-action@v2
        continue-on-error: true

      - name: List discovered Gradle wrappers (debug)
        if: always()
        run: |
          echo "Wrapper property files:" && git ls-files | grep -E 'gradle-wrapper.properties$' || true
          echo "Wrapper jar files:" && git ls-files | grep -E 'gradle-wrapper.jar$' || true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build (no tests)
        run: ./gradlew --no-daemon clean build -x test

      - name: Test
        run: ./gradlew --no-daemon test

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test

      - name: Check results path
        if: always()
        run: ls -R build/test-results || true

      - name: Publish JUnit results
        if: always() && hashFiles('build/test-results/test/*.xml') != ''
        uses: dorny/test-reporter@v1
        with:
          name: JUnit Tests
          path: build/test-results/test/*.xml
          reporter: java-junit
          fail-on-error: true

      - name: No test result files found notice
        if: always() && hashFiles('build/test-results/test/*.xml') == ''
        run: |
          echo "No JUnit XML files found at build/test-results/test/*.xml."
          echo "If tests should run, verify the Gradle task and that they are not skipped."
