name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 👇 add this block
permissions:
  contents: read
  checks: write
  # (optional if you want PR comments)
  # pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build & Test
        run: ./gradlew --no-daemon clean test

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test

      # optional: verify test results path exists (useful when tests are skipped/fail early)
      - name: Check results path
        if: always()
        run: ls -R build/test-results || true

      - name: Publish JUnit results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: JUnit Tests
          path: build/test-results/test/*.xml
          reporter: java-junit
